#!/bin/bash

# Install desktop tools

sudo apt-get install xrdp ssh freerdp2-x11 freerdp2-shadow-x11 terminator -y
sudo systemctl start xrdp
sudo systemctl start xrdp-sesman
sudo systemctl enable xrdp
sudo systemctl enable xrdp-sesman
sudo systemctl start ssh
sudo systemctl enable ssh.service
