#!/bin/bash

# Add CyberBoNBoN user with sudo permissions
sudo su -
#adduser cyberbonbon --disabled-password --gecos ""
adduser cyberbonbon --gecos ""
test123
test123


usermod -aG sudo cyberbonbon
exit

# Copy the Apt-cacher-NG proxy configuration
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/gondor_cache
sudo chown root:root gondor_cache
sudo mv gondor_cache /etc/apt/apt.conf.d/01proxy

# Perform a system update
sudo apt-get update && sudo apt-get dist-upgrade -y

# Disable NTP while configuring new settings
sudo timedatectl set-ntp off

# Install default tools
sudo apt-get install smartmontools nfs-common apt-transport-https ca-certificates gnupg-agent software-properties-common snmpd chrony qemu-guest-agent mtr net-tools autofs -y

# Copy the default sshd configuration file
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/sshd_config
sudo chown root:root sshd_config
sudo chmod 644 sshd_config
sudo mv sshd_config /etc/ssh/sshd_config

# Copy the approved list of authorized SSH keys, create the .ssh user directory and move the file to it
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/authorized_keys
sudo mkdir /home/cyberbonbon/.ssh
sudo chown cyberbonbon:cyberbonbon /home/cyberbonbon/.ssh
sudo chown cyberbonbon:cyberbonbon authorized_keys
sudo mv authorized_keys /home/cyberbonbon/.ssh/authorized_keys

# Copy SNMP configuration template
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/gondor.snmpd.conf
sudo chown root:root gondor.snmpd.conf
sudo chmod 644 gondor.snmpd.conf
sudo mv gondor.snmpd.conf /etc/snmp/snmpd.conf

# Copy SNMP override
sudo mkdir -p /etc/systemd/system/snmpd.service.d
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/override.conf
sudo chown root:root override.conf
sudo chmod 644 override.conf
sudo mv override.conf //etc/systemd/system/snmpd.service.d/override.conf

# Copy Chrony NTP configuration and set the time zone
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/chrony.conf
sudo chown root:root chrony.conf
sudo chmod 644 chrony.conf
sudo mv chrony.conf /etc/chrony/chrony.conf

# Gondor time zone
sudo timedatectl set-timezone America/Chicago

# Turn on Chrony NTP
sudo systemctl enable --now chrony
sleep 5
sudo timedatectl set-ntp on

# Create Mounts for NFS shares
sudo mkdir -p /nfs/MinasTirith/
sudo mkdir -p /nfs/Ecthelion/

# Configure auto.master
echo `/nfs /etc/auto.nfs --timeout=30` | sudo tee -a /etc/auto.master

# Create auto.nfs file
echo '# NFS Access Shares' | sudo tee -a /etc/auto.nfs
echo `MinasTirith  -rw,soft,timeo=10,retrans=3,nofail  minastirith.gondor.middleearth.network:/mnt/user/Backups` | sudo tee -a /etc/auto.nfs
echo `Ecthelion    -rw,soft,timeo=10,retrans=3,nofail  ecthelion.gondor.middleearth.network:/certs/$HOSTNAME.gondor.middleearth.network` | sudo tee -a /etc/auto.nfs

# Restart and enable autofs
sudo systemctl restart autofs
sudo systemctl enable autofs

# Copy cert script and enable chron job
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/cert.sh
sudo chown root:root cert.sh
sudo chmod 755 cert.sh
sudo mv cert.sh /usr/bin/cert.sh
echo -e "$(sudo crontab -u root -l)\n0 5 * * 1 /usr/bin/cert.sh && systemctl restart nginx" | sudo crontab -u root -
sudo /usr/bin/cert.sh

# Wait a period and reboot
sleep 30
reboot
