#!/bin/bash

# Add CyberBoNBoN user with sudo permissions
adduser cyberbonbon --disabled-password --gecos ""

#adduser cyberbonbon --gecos "" --disabled-password
#echo "myuser:password" | sudo chpasswd

#test123
#test123
#Shawn
#0
#0
#0
#0
#y

usermod -aG sudo cyberbonbon

# Copy the Apt-cacher-NG proxy configuration
#wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/gondor_cache
#sudo chown root:root gondor_cache
#sudo mv gondor_cache /etc/apt/apt.conf.d/01proxy

# Perform a system update
sudo apt-get update && sudo apt-get dist-upgrade -y

# Disable NTP while configuring new settings
sudo timedatectl set-ntp off

# Install default tools
sudo apt-get install smartmontools nfs-common apt-transport-https ca-certificates gnupg-agent software-properties-common snmpd chrony open-vm-tools mtr net-tools -y

# Copy the default sshd configuration file
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/sshd_config
sudo chown root:root sshd_config
sudo chmod 644 sshd_config
sudo mv sshd_config /etc/ssh/sshd_config

# Copy the approved list of authorized SSH keys, create the .ssh user directory and move the file to it
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/authorized_keys
mkdir /user/cyberbonbon/.ssh
sudo chown cyberbonbon:cyberbonbon /user/cyberbonbon/.ssh
sudo chown cyberbonbon:cyberbonbon authorized_keys
mv authorized_keys /user/cyberbonbon.ssh/authorized_keys

# Copy SNMP configuration template
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/gondor.snmpd.conf
sudo chown root:root gondor.snmpd.conf
sudo chmod 644 gondor.snmpd.conf
sudo mv gondor.snmpd.conf /etc/snmp/snmpd.conf

# Copy Chrony NTP configuration and set the time zone
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/chrony.conf
sudo chown root:root chrony.conf
sudo chmod 644 chrony.conf
sudo mv chrony.conf /etc/chrony/chrony.conf

# Gondor time zone
sudo timedatectl set-timezone America/New_York

# Turn on Chrony NTP
sudo systemctl enable --now chrony
sleep 5
sudo timedatectl set-ntp on

# After update for remote: Copy the Apt-cacher-NG proxy configuration
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/gondor_cache
sudo chown root:root gondor_cache
sudo mv gondor_cache /etc/apt/apt.conf.d/01proxy

# Wait a period and reboot
sleep 30
reboot
