#!/bin/bash

# Hardcode hostname in /etc/hosts
echo -e "127.0.0.1 $HOSTNAME\n$(cat /etc/hosts)" > /etc/hosts

# Add CyberBoNBoN user with sudo permissions
adduser cyberbonbon --disabled-password --gecos ""
usermod -aG sudo cyberbonbon

# Perform a system update
apt-get update && sudo apt-get dist-upgrade -y

# Disable NTP while configuring new settings
timedatectl set-ntp off

# Install default tools
apt-get install wireguard wireguard-tools smartmontools nfs-common apt-transport-https ca-certificates gnupg-agent software-properties-common snmpd chrony open-vm-tools mtr net-tools -y

# Copy the default sshd configuration file
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/sshd_config
chown root:root sshd_config
chmod 644 sshd_config
mv sshd_config /etc/ssh/sshd_config

# Copy the approved list of authorized SSH keys, create the .ssh user directory and move the file to it
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/authorized_keys
mkdir /home/cyberbonbon/.ssh
chown cyberbonbon:cyberbonbon /home/cyberbonbon/.ssh
chown cyberbonbon:cyberbonbon authorized_keys
mv authorized_keys /home/cyberbonbon/.ssh/authorized_keys

# Copy SNMP configuration template
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/gondor.snmpd.conf
chown root:root gondor.snmpd.conf
chmod 644 gondor.snmpd.conf
mv gondor.snmpd.conf /etc/snmp/snmpd.conf

# Copy Chrony NTP configuration and set the time zone
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/chrony.conf
chown root:root chrony.conf
chmod 644 chrony.conf
mv chrony.conf /etc/chrony/chrony.conf

# Gondor time zone
timedatectl set-timezone America/New_York

# Turn on Chrony NTP
systemctl enable --now chrony
sleep 5
timedatectl set-ntp on

# Wireguard Key Generation and template download
mkdir -p /etc/wireguard/clients
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/wg01.conf
mv wg01.conf /etc/wireguard/wg01.conf
wg genkey | sudo tee /etc/wireguard/clients/$HOSTNAME.key | wg pubkey | sudo tee /etc/wireguard/clients/$HOSTNAME.key.pub

# Add private key to wg01 configuration
echo -e "[Interface]\nPrivateKey = $(cat /etc/wireguard/clients/$HOSTNAME.key)\n$(cat /etc/wireguard/wg01.conf)" > /etc/wireguard/wg01.conf

# Configure Wireguard to start on boot
systemctl enable wg-quick@wg01.service

# Configure DNS
echo -e "$(sudo crontab -u root -l)\n@reboot wget -O /run/systemd/resolved.conf.d/dns-wg01.conf https://raw.githubusercontent.com/cyberbonbon/linux_install/main/dns-wg01.conf\n@reboot sleep 10 service systemd-resolved restart" | sudo crontab -u root -

#
# End of script
