#!/bin/bash

# Reset Host SSH Keys
sudo rm -rf /etc/ssh/ssh_host_*
sudo dpkg-reconfigure openssh-server

# Copy the Apt-cacher-NG proxy configuration
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/gondor_cache
sudo chown root:root gondor_cache
sudo mv gondor_cache /etc/apt/apt.conf.d/01proxy

# Perform a system update
sudo apt-get update && sudo apt-get dist-upgrade -y

# Disable NTP while configuring new settings
sudo timedatectl set-ntp off

# Install default tools
sudo apt-get install smartmontools nfs-common apt-transport-https ca-certificates gnupg-agent software-properties-common snmpd ntp open-vm-tools terminator -y

# Copy the default sshd configuration file
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/sshd_config
sudo chown root:root sshd_config
sudo chmod 644 sshd_config
sudo mv sshd_config /etc/ssh/sshd_config

# Copy the approved list of authorized SSH keys, create the .ssh user directory and move the file to it
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/authorized_keys
mkdir .ssh
sudo chown cyberbonbon:cyberbonbon authorized_keys
mv authorized_keys .ssh/authorized_keys

# Copy NTP configuration and set the time zone
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/ntp.conf
sudo chown root:root ntp.conf
sudo chmod 644 ntp.conf
sudo mv ntp.conf /etc/ntp.conf

# Gondor time zone
sudo timedatectl set-timezone America/New_York

# Create Mounts for NFS shares
sudo mkdir -p /nfs/MinasTirith/CyberSecurityClubStorage
sudo mkdir -p /nfs/MinasTirith/CyberSecurityReadOnly


sudo echo 'morannon.gondor.middleearth.network:/mnt/user/CyberSecurityClubStorage    /nfs/MinasTirith/CyberSecurityClubStorage   nfs lookupcache=none,bg,lock,proto=tcp   0 0' >> /etc/fstab
sudo echo 'morannon.gondor.middleearth.network:/mnt/user/CyberSecurityReadOnly    /nfs/MinasTirith/CyberSecurityReadOnly   nfs lookupcache=none,bg,lock,proto=tcp   0 0' >> /etc/fstab
sudo mount -av
