#!/bin/bash

# Add CyberBoNBoN user with sudo permissions
adduser cyberbonbon --disabled-password --gecos ""
usermod -aG sudo cyberbonbon

# Pause for auto updates
sleep 60

# Perform a system update
sudo apt-get update && sudo apt-get -o Dpkg::Options::="--force-confold" dist-upgrade -y

# Disable NTP while configuring new settings
timedatectl set-ntp off

# Install default tools
sudo apt-get install -o Dpkg::Options::="--force-confold" wireguard wireguard-tools smartmontools nfs-common apt-transport-https ca-certificates gnupg-agent software-properties-common snmpd chrony open-vm-tools mtr net-tools -y

# Hardcode hostname in /etc/hosts
echo "127.0.0.1 $HOSTNAME" >> /etc/hosts

# Copy the default sshd configuration file
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/sshd_config
chmod 644 sshd_config
mv sshd_config /etc/ssh/sshd_config

# Copy the approved list of authorized SSH keys, create the .ssh user directory and move the file to it
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/authorized_keys
mkdir /home/cyberbonbon/.ssh
chown cyberbonbon:cyberbonbon /home/cyberbonbon/.ssh
chown cyberbonbon:cyberbonbon authorized_keys
mv authorized_keys /home/cyberbonbon/.ssh/authorized_keys

# Copy SNMP configuration template
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/gondor.snmpd.conf
chmod 644 gondor.snmpd.conf
mv gondor.snmpd.conf /etc/snmp/snmpd.conf

# Copy Chrony NTP configuration and set the time zone
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/chrony.conf
chmod 644 chrony.conf
mv chrony.conf /etc/chrony/chrony.conf

# Gondor time zone
timedatectl set-timezone America/New_York

# Turn on Chrony NTP
systemctl enable --now chrony
sleep 5
timedatectl set-ntp on

# Wireguard Key Generation and template download
mkdir -p /etc/wireguard/clients
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/wg01.conf
mv wg01.conf /etc/wireguard/wg01.conf
wg genkey | sudo tee /etc/wireguard/clients/$HOSTNAME.key | wg pubkey | sudo tee /etc/wireguard/clients/$HOSTNAME.key.pub

# Add private key to wg01 configuration
echo -e "[Interface]\nPrivateKey = $(cat /etc/wireguard/clients/$HOSTNAME.key)\n$(cat /etc/wireguard/wg01.conf)" > /etc/wireguard/wg01.conf

# Configure Wireguard to start on boot
systemctl enable wg-quick@wg01.service

# Configure DNS and Crontab entries 
wget -O /etc/dns-wg01.conf https://raw.githubusercontent.com/cyberbonbon/linux_install/main/dns-wg01.conf
echo -e "$(sudo crontab -u root -l)\n@reboot cp /etc/dns-wg01.conf /run/systemd/resolved.conf.d/dns-wg01.conf\n@reboot sudo service systemd-resolved restart\n@reboot sleep 30 && sudo mount -av" | sudo crontab -u root -

# Create Mounts for NFS shares
sudo mkdir -p /nfs/MinasTirith/

# Append NFS mounts to fstab file
echo '# NFS Shares' | sudo tee -a /etc/fstab
echo 'minastirith.gondor.middleearth.network:/mnt/user/Backups    /nfs/MinasTirith/   nfs soft,timeo=600,lookupcache=none,bg,lock,proto=tcp   0 0' | sudo tee -a /etc/fstab

# Configuration for delayed NFS mount
#wget -O /usr/bin/nfs_delayed_mount.sh https://raw.githubusercontent.com/cyberbonbon/linux_install/main/nfs_delayed_mount.sh
#wget -O /etc/rc.local https://raw.githubusercontent.com/cyberbonbon/linux_install/main/rc.local_delayed_NFS
#chmod +x /usr/bin/nfs_delayed_mount.sh

#
# End of script
