#!/bin/bash

# Wireguard Key Generation and template download
sudo mkdir -p /etc/wireguard/clients
wget https://raw.githubusercontent.com/cyberbonbon/linux_install/main/wg01.conf
sudo mv wg01.conf /etc/wireguard/wg01.conf
sudo wg genkey | sudo tee /etc/wireguard/clients/$HOSTNAME.key | wg pubkey | sudo tee /etc/wireguard/clients/$HOSTNAME.key.pub

# Add private key to wg01 configuration
sudo echo -e "[Interface]\nPrivateKey = $(cat /etc/wireguard/clients/$HOSTNAME.key)\n$(cat /etc/wireguard/wg01.conf)" > /etc/wireguard/wg01.conf

# Configure Wireguard to start on boot
systemctl enable wg-quick@wg01.service

# Advertise public key

sudo echo -e "\n\n\n\nPublic key to add to server:\n\n$(sudo cat /etc/wireguard/clients/$HOSTNAME.key.pub)\n\nEdit the IP address for this host sudo vi /etc/wireguard/wg01.conf\n\nThen run:\n\nsudo wg-quick up wg01\n\n\n"

#
# End of file
